name = "cf-mcp"
main = "src/index.ts"
compatibility_date = "2024-03-27"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "brain_db"
database_id = "d0e79229-5505-43e4-8d0c-adf994776e08"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "brain_vectors"

[[services]]
binding = "TELEMETRY_SERVICE"
service = "cf-telemetry"
